baseurl = "https://attajak.netlify.app"
DefaultContentLanguage = "en"
title = "Attajak"
# Using theme as git submodule 
# theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = true
pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[modules]
  [[module.imports]]
  path = "github.com/halogenica/beautifulhugo"

[Params]
  # homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "https://attajak.netlify.app"
  mainSections = ["post","posts"]
  logo = "favicon/android-chrome-512x512.png" # Expecting square dimensions
  favicon = "favicon/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

[[Params.bigimg]]
  src = "img/triangle.jpg"
  desc = "Triangle"
[[Params.bigimg]]
  src = "img/sphere.jpg"
  desc = "Sphere"
  # position: see values of CSS background-position.
  position = "center top"
[[Params.bigimg]]
  src = "img/hexagon.jpg"
  desc = "Hexagon"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Attajak Janrak"
  website = "https://attajak.github.io"
  email = "janrak@gmail.com"
  facebook = "attajak"
  github = "attajak"
  gitlab = "attajak"
  bitbucket = "attajak"
  twitter = "attajak"
  reddit = "attajak"
  linkedin = "attajak"
  # xing = "username"
  # stackoverflow = "users/XXXXXXX/username"
  snapchat = "attajak"
  instagram = "attajak"
  youtube = "@attajak" # or channel/channelname
  soundcloud = "attajak"
  spotify = "attajak"
  # bandcamp = "username"
  # itchio = "username"
  vk = "attajak"
  paypal = "attajak"
  telegram = "attajak"
  500px = "attajak"
  codepen = "attajak"
  mastodon = "https://mastodon.in.th/@attajak"
  # kaggle = "username"
  # weibo = "username"
  # slack = "username"
  medium = "attajak"
  # discord = "invite code (https://discord.gg/XXXXXXX)"
  # strava = "userid"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    weight = 2
    
[[menu.main]]
    parent = "blog"
    name = "Posts"
    url = "posts"
    weight = 1

[[menu.main]]
    parent = "blog"
    name = "Categories"
    url = "categories"
    weight = 2

[[menu.main]]
    parent = "blog"
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    identifier = "about"
    name = "About"
    weight = 3

[[menu.main]]
    parent = "about"
    name = "About"
    url = "about"
    weight = 1

[[menu.main]]
    parent = "about"
    name = "Contact"
    url = "contact"
    weight = 2
