[build]
  # command = "hugo --gc --minify --logLevel info"
  # functions = "netlify/functions"
  publish = "public"

[build.environment]
NODE_VERSION = "22.11.0"
HUGO_VERSION = "0.139.5"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "1.23.0"

[context.production]
command = "hugo --logLevel info --gc --minify"

[context.production.environment]
HUGO_ENV = "production"
