[build]
  # command = "hugo --gc --minify --logLevel info"
  # functions = "netlify/functions"
  publish = "public"

[build.environment]
NODE_VERSION = "22.13.1"
NPM_VERSION = "10.9.2"
HUGO_VERSION = "0.145.0"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "1.24.0"

[context.production]
command = "hugo --gc --minify --logLevel info"

[context.production.environment]
HUGO_ENV = "production"
