[build]
  # command = "hugo --gc --minify --logLevel info"
  # functions = "netlify/functions"
  publish = "public"

[build.environment]
NODE_VERSION = "22.11.0"
NPM_VERSION = "10.9.2"
HUGO_VERSION = "0.141.0"
HUGO_EXTENDED = "true"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "^1.23.0"

[context.production]
# command = "hugo --gc --minify --logLevel info"
command = "npm run build"

[context.production.environment]
HUGO_ENV = "production"
